### ISSUE TITLE
EventCallback functions not called

### ISSUE THREAD

**Issue by roboryantron** [slightech/MYNT-SDK-Android#1]
In the provided demo, the callbacks for ClickEvents are never called. The expected behavior is that when the Mynt button is clicked, the eventFired function would be triggered with the ClickeEvent that was performed on the device.

public void eventFired(Device device, ClickEvent event)

**Comment by joinAero** [comment]
MYNT has two connect mode: HID & BLE. In HID mode, another `eventFired` function will be triggered.

```
    /**
     * What click event is fired in {@link ConnectMode#CONNECT_BLE} mode.
     *
     * @param device the device
     * @param event the click event
     */
    void eventFired(Device device, ClickEvent event);

    /**
     * What action event is fired in {@link ConnectMode#CONNECT_HID} mode.
     *
     * @param device the device
     * @param event the action event
     */
    void eventFired(Device device, ActionEvent event);
```

The doc is [here](https://github.com/slightech/MYNT-SDK-Android/tree/master/doc).

In HID mode, now you could `sendControlCustomClicks` to do this. It‘s equivalent to:

```
sendControlMode(ControlMode.CONTROL_MODE_CUSTOM);
sendControlCustomAction(MYNT.sn, Action {
  click:             ActionEvent.ACTION_CLICK,
  doubleClick: ActionEvent.ACTION_DOUBLE_CLICK,
  tripleClick:    ActionEvent.ACTION_TRIPLE_CLICK,
  longClick:     ActionEvent.ACTION_LONG_CLICK,
  clickHold:     ActionEvent.ACTION_CLICK_HOLD,
});
```

Then handle the clicks as the following:

```
void eventFired(Device device, ActionEvent event) {
  switch(event) {
    case ActionEvent.ACTION_CLICK: doClick(); break;
    ......
  }
}
```

You could try the latest demo now.

**Comment by VincentPLM** [comment]
Hello roboryantron,

Where you successfull of catching the eventFired with the demo SDK?

I'm also trying... Would love to have some code that works.

Thank you,

VIncent;

**Comment by roboryantron** [comment]
I was using this for a project a while back and gave up on it after running
into issues, so I am not working with it anymore and I do not have any code
using it at the moment.
