### ISSUE TITLE
Open application xyz

### ISSUE THREAD

**Issue by VincentPLM** [slightech/MYNT-SDK-Android#2]
Hello,

I bought my MYNT thinking it would be easy to chose what application to launch when a button is clicked.

How can I tell MYNT to launch let say Google Map when I do a single click? Do I need to work with the SKD for that?

Thank you,

Vincent;

**Comment by txtGenius** [comment]
Hi Vincent,

Thanks for supporting MYNT. It's a very simple for your solution with SDK.

You can set up with the following order:
1. Disable HID connection mode when initializing SDK, you can set up with `MyntManager.setAllowConnectSysHID(false);`
2. Implement `EventCallback` and register to MyntManager with `MyntManager.setEventCallback(EventCallback callback);`
3. Then you will receive MYNT click event in the callback of `eventFired(Device device, ClickEvent event);` in EventCallback.
4. Check the `event` parameter of the callback. If it's `ClickEvent.Click`, then it's where you are looking for.  You can lanuch Google Map here.

Best Regards
Shion

**Comment by VincentPLM** [comment]
Hello,

Thank you for your answer. I was not into it anymore between the time I asked the question and received the answer.  

Now I try to get back at it.

I don't find the mentioned method: setAllowConnectSysHID. It's in the API documentation and it's doesn't compile when I'm tring to use it.

From the DEMO apk, I tried to modified use the class ControlActivity who already implement EventCallback.

When the DEMO start, I see the traces from ControlActivity. However, I don't see none of the traces from the event methods. (eventActionChanged, eventInfoChanged, eventFired.) I tried click, double click, long hold the Mynt, 

As you suggested, I tried to add: mMyntManager.setEventCallback(this);. I tried to put it in intObjects(), keyStored() and connect() method of the class ControlActivity. (Because I see the trace from those method).

Still, nothing happening when I click on the device. 


As you can see in the following screenshot, the connection works:
I do see the eventBatteryChange after a while...
![traces](https://user-images.githubusercontent.com/25524930/30523289-3bcd4fa2-9bdf-11e7-85ab-0d5c854b9cd2.png)



Can you please help me to figure out why I don't see the traces in the “evenFired” method?

Thank you,

Vincent;
