### ISSUE TITLE
关于api的callback的使用

### ISSUE THREAD

**Issue by SiriusYZ** [slightech/MYNT-SDK-Android#3]
你好，我运行了你们的demo，也自己做了一个demo，发现MYNT与手机超出可连接距离之后，没有回调监听到手机蓝牙与MYNT的连接已断开。请帮助解决这个问题，望尽快回复，谢谢！

**Comment by wanglu0919** [comment]
mynt-sdk 监听不到距离的远近，在远距离时，蓝牙可能并没有断开。只有在蓝牙断开的时候会回调pairDisconnect 函数。

**Comment by gejw0623** [comment]
1
