### ISSUE TITLE
Can't use the Event from the DEMO apk

### ISSUE THREAD

**Issue by VincentPLM** [slightech/MYNT-SDK-Android#4]
Hello,

Thank you for your answer. I was not into it anymore between the time I asked the question and received the answer.  

Now I try to get back at it.

I don't find the mentioned method: setAllowConnectSysHID. It's in the API documentation and it's doesn't compile when I'm tring to use it.

From the DEMO apk, I tried to modified use the class ControlActivity who already implement EventCallback.

When the DEMO start, I see the traces from ControlActivity. However, I don't see none of the traces from the event methods. (eventActionChanged, eventInfoChanged, eventFired.) I tried click, double click, long hold the Mynt, 

As you suggested, I tried to add: mMyntManager.setEventCallback(this);. I tried to put it in intObjects(), keyStored() and connect() method of the class ControlActivity. (Because I see the trace from those method).

Still, nothing happening when I click on the device. 

As you can see in the  screenshot below, the connection works:
I do see the eventBatteryChange after a while...

Can you please help me to figure out why I don't see the traces in the “evenFired” method?

Thank you,

Vincent;
![traces](https://user-images.githubusercontent.com/25524930/30523308-addc8c98-9bdf-11e7-8372-58f7e84ea416.png)

**Comment by txtGenius** [comment]
I think before these operation, there are some preparation to do. 

This issue is similar as yours, it may be helpful:
[[Issue]EventCallback functions not called](https://github.com/slightech/MYNT-SDK-Android/issues/1)

By the way, `MyntManager.setAllowConnectSysHID()` method mentioned is still in our development branch now. We will release a new SDK version recently.

Thanks

**Comment by VincentPLM** [comment]
Hello DarkAtlantis,
Thank you, i will try that.
Vincent;

**Comment by VincentPLM** [comment]
Hello DarkAtlantis,

I can't compile as suggested in the answer.

I putted my code in the menu of ControlActivity.java under: "case R.id.send_control_mode:". 

Once the application is launched, I wanted to select from the menu: "Send control mode" 

The the following code would be executed: 

pStrong("calling mMyntManager.setupConnectBLE");
mMyntManager.setupConnectBLE(mDeviceSn);
mMyntManager.sendControlCustomAction(mDeviceSn, Action {
              click : ActionEvent.ACTION_CLICK,
            doubleClick: ActionEvent.ACTION_DOUBLE_CLICK,
            tripleClick:    ActionEvent.ACTION_TRIPLE_CLICK,
            longClick:     ActionEvent.ACTION_LONG_CLICK,
            clickHold:     ActionEvent.ACTION_CLICK_HOLD,
});


I tried different things. (Device.Action...) But it doesn't work.

I would be great if we could have a demo that works out of the box. 
A demo where we see the following trace when we click on the button:
    @Override
    public void eventFired(Device device, ActionEvent event) {
        pInfo("eventFired ActionEvent: %s", event.name());
    }

From there then we can add stuff under the eventFired.

Anyway, please see if you can help me. Here a screenshot and the class I use in the demo. You will see that I make sure to see the menu. For some reason the bound finish at false... (after three/four inits... (see screenshot)


Thank you,

Vincent;


![bound finish at false](https://user-images.githubusercontent.com/25524930/30616075-4f9a6944-9d91-11e7-9488-6a3fbd05865f.png)
)


![image](https://user-images.githubusercontent.com/25524930/30615442-490451a0-9d8f-11e7-9eb3-745b920c2441.png)

**Comment by VincentPLM** [comment]
This is building, still, not working....
[ControlActivity.java.txt](https://github.com/slightech/MYNT-SDK-Android/files/1315983/ControlActivity.java.txt)

**Comment by txtGenius** [comment]
Hi Vincent,

I've read your code, I suggest to set customize action like this:
```
new AlertDialog.Builder(this)
       .setTitle(R.string.send_control_mode)
       .setItems(R.array.control_modes, new DialogInterface.OnClickListener() {
           @Override
            public void onClick(DialogInterface dialog, int which) {
                ControlMode mode = ControlMode.get(which + 1);
                pStrong(getString(R.string.send_control_mode) + " " + mode.name());
                mMyntManager.sendControlMode(mDeviceSn, mode);

                Device myDevice =  mMyntManager.findDevice(mDeviceSn);
                mMyntManager.sendControlCustomAction(mDeviceSn, myDevice.action);
                mMyntManager.setEventCallback(this);

                updateInfo(mDeviceSn, mode);
              }
          })
         .show();
pStrong("calling mMyntManager.setupConnectBLE");
mMyntManager.setupConnectBLE(mDeviceSn);
```

The `sendControlMode()` must execute before `sendControlCustomAction()`. 

I notice that your mynt software version is 29, this is latest version. If that solution still not work, please wait for new SDK. We will release recently.

Thanks,
Shion

**Comment by VincentPLM** [comment]
Thank you for your answer Shion.

I can't compile if I put the statement "mMyntManager.setEventCallback(this);" inside the definition  of the class AlertDialog.Builder.

See:

![this is not accessible](https://user-images.githubusercontent.com/25524930/30667906-56d6f16e-9e59-11e7-8951-c6db395590a0.png)

**Comment by VincentPLM** [comment]
I tried the following now. Still not working. (note that I change menu.)

            case R.id.request_control_custom_action:
                pStrong(getString(R.string.request_control_custom_action));

                mMyntManager.sendControlMode(mDeviceSn, ControlMode.CONTROL_MODE_CUSTOM);

                mMyntManager.requestControlCustomAction(mDeviceSn);

                Device myDevice =  mMyntManager.findDevice(mDeviceSn);
                mMyntManager.sendControlCustomAction(mDeviceSn, myDevice.action);

                mMyntManager.setEventCallback(this);

                pStrong("calling mMyntManager.setupConnectBLE");
                mMyntManager.setupConnectBLE(mDeviceSn);

                break;

**Comment by VincentPLM** [comment]
ok... I push the firmware 26 back and use the code that I posted in the previous command. Now I see the event click!

The right firmware version need to be used with this set of API.

Thank you!

Will keep an eye open for the new demo kit!

Vincent;

**Comment by txtGenius** [comment]
Hi Vincent,

Thanks for supporting MYNT and give us great suggestion.

Best Regards 
Shion
