### ISSUE TITLE
Is it possible to add custom actions in the actions list?

### ISSUE THREAD

**Issue by VincentPLM** [slightech/MYNT-SDK-Android#5]
Hello,

The Mynt application come with a list of actions that can be associated to click:
Take Picture, Burst shot, Next song, Next page, Flash light, etc...
(See screenshot below)

I would like to know if I can add actions in that list... Like:
-Open camera app, Start filming
-Open sound app, Start recording
-etc...

Is there a way to simply do that?

Can we list them in a xml file and have them load by the Mynt app?

Can we have the Mynt app to modify it and add the actions we want?

Thank you,

Vincent;

![available actions](https://user-images.githubusercontent.com/25524930/30523775-a7517df4-9be7-11e7-9c06-8988245144ce.png)

**Comment by txtGenius** [comment]
For current MYNT application, the function of customize click event is not available yet. But your suggestion is great. We will take it into MYNT application in the future. 

And now MYNT SDK is still the best way to customize click event. The other issue is in the process right now.

Thanks a lot.

**Comment by VincentPLM** [comment]
Hello DarkAtlantis,

Thank you for your fast response. The other issue in process; do you mean Mynt it's considering opening the application? Opening the application to public would allow us to improve it.

Thank you

Vincent;

**Comment by txtGenius** [comment]
Hi Vincent,

"The other issue in process", I mean that issue you opened([[Issue #4] Can't use the Event from the DEMO apk](https://github.com/slightech/MYNT-SDK-Android/issues/4)) is being processed right now.

At the other hand, we take MYNT application for commercial use, so it may not open to public. But Mynt has a strong team to maintain it, we have quite confidence to meet your needs.

Thanks
Shion;

**Comment by VincentPLM** [comment]
Ok, thank you.
